Tidy deployment script (#48)
* Update deploy

* Create goerli.deployments.txt

* Bump versions

* Update deploy

* Nile with modern CLI call

* Update goerli.deployments.txt

* Error logs

The deploy functions are inactivated temporarily

* Remove error notes

Resolved with Nile PR43 (tested locally)

* Add error in call to Arbiter

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,33 +1,31 @@
 #!/bin/bash
 set -eu
 
+###########################################
+#               Network                   #
+###########################################
+
+# For a network_type=localhost node open a new shell and run:
+# `nile node`
+
+# network_type=localhost
+network_type=goerli
+# network_type=mainnet
+
+
 # Flow:
 ## The Controller is the only unchangeable contract.
 ## First deploy Arbiter.
 ## Then send the Arbiter address during Controller deployment.
 ## Then deploy Controller address during module deployments.
 
-# TODO: For a network_type node open a new shell and run:
-# Need to incorporate this into the script.
-# `nile node`
-
-# Network:
-network_type=localhost
-# network_type=mainnet
-
-# localhost is a ShardLabs devnet locally.
-# mainnet is currently Goerli/StarkNet-alpha
-
-
 # Wipe old deployment record if it exists.
-rm $network_type.deployments.txt || $echo 'Will create one...'
+rm $network_type.deployments.txt || echo 'Will create one...'
 
-
+# Searches for a keyword, then fetches the address from that line.
 get_address () {
-    # TODO read deployment address from $network_type.deployments.txt
-    # Find the line containing the alias $1.
-    # grep -o -m 1 '\b0x\w*'
-    # echo result.
+    echo $(grep $1 $network_type.deployments.txt | \
+        grep -o -m 1 '\b0x\w*')
 }
 
 # Public keys of wallets (dummy/placeholder)
@@ -35,26 +33,38 @@ declare -i AdminPubKey=12345678987654321
 declare -i User00PubKey=456456456
 
 # Admin account contract
-AdminAccount=nile deploy Account $AdminPubKey \
-    --alias AdminAccount --network $network_type
-AdminAddress=$(get_address AdminAccount)
+AdminAccount=$(nile deploy Account $AdminPubKey \
+    --alias AdminAccount --network $network_type)
 
 # Arbiter contract (controlled by Admin)
-Arbiter=nile deploy Arbiter $AdminAddress \
-    --alias Arbiter --network $network_type
-ArbiterAddress=$(get_address Arbiter)
+Arbiter=$(nile deploy Arbiter $(get_address "AdminAccount") \
+    --alias Arbiter --network $network_type)
 
 # Module controller contract (controlled by Arbiter)
-ModuleController=nile deploy ModuleController $ArbiterAddress \
-    --alias ModuleController --network $network_type
-ModuleControllerAddress=$(get_address ModuleController)
+ModuleController=$(nile deploy ModuleController $(get_address "Arbiter") \
+    --alias ModuleController --network $network_type)
 
+# Save address of controller into the arbiter
+echo "invoking contract:" $(get_address "Arbiter")
+nile invoke Arbiter set_address_of_controller \
+    $(get_address "ModuleController") --network $network_type
+
+# Tx failed. Hash: 0x77cc8ff0af3fc65532577e17e420d2db9fda60bf7e4cf11ddf0286aa9d51aa5
+
+# The admin account will control the Arbiter
+# and will be deployed with STARK-friendly ECDSA keypair(s). The
+# key(s) will then be used to sign messages that go to the Account.
+# The Account checks the signature(s) then passes the transaction data
+# to the Arbiter. The Arbiter may then do things like call the
+# ModuleController with information about a new module address.
+
+###########################################
+#                Modules                  #
+###########################################
 # The constructor of each module is passed the address of the controller.
 deploy_module () {
-    nile deploy $1 $ModuleControllerAddress \
+    nile deploy $1 $(get_address "ModuleController") \
         --alias $1 --network $network_type
-    address=$(get_address $1)
-    # TODO Export this as "module$1" to be later sent to the controller.
 }
 
 # Deploy each module.
@@ -66,27 +76,21 @@ deploy_module "05_Combat"
 deploy_module "06_DrugLord"
 deploy_module "07_PseudoRandom"
 
+# Use the Arbiter to save module addresses into the ModuleController.
+echo "invoking contract:" $(get_address "ModuleController")
+nile invoke ModuleController set_initial_module_addresses \
+    $(get_address "1_DopeWars") \
+    $(get_address "2_LocationOwned") \
+    $(get_address "3_UserOwned") \
+    $(get_address "4_UserRegistry") \
+    $(get_address "5_Combat") \
+    $(get_address "6_DrugLord") \
+    $(get_address "7_PseudoRandom") \
+    --network $network_type
 
-# The admin account will control the Arbiter
-# and will be deployed with STARK-friendly ECDSA keypair(s). The
-# key(s) will then be used to sign messages that go to the Account.
-# The Account checks the signature(s) then passes the transaction data
-# to the Arbiter. The Arbiter may then do things like call the
-# ModuleController with information about a new module address.
-
-
+###########################################
+#                Player(s)                #
+###########################################
 nile deploy Account $User00PubKey \
     --alias User00Account --network $network_type
-
-# Save address of controller into the arbiter
-nile invoke Arbiter set_address_of_controller $ModuleControllerAddress
-
-# These could be fetched from the deployments.txt files which
-# would make the above deploy commands simpler.
-# Use the Arbiter to save module addresses into the ModuleController.
-nile invoke ModuleController set_initial_module_addresses \
-    $module_01_DopeWars module_02_LocationOwned \
-    $module_03_UserOwned module_04_UserRegistry \
-    $module_05_Combat module_06_DrugLord \
-    $module_07_PseudoRandom
 
